### ISSUE TITLE
Add Next.js plugin to ESLint configuration

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#103]
I noticed this error in [a PR](https://vercel.com/margaritahumanitarian/helpafamily/7aG4hausAKsqhcgEzmMAMAWq11Ez) today:

> warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config

**Comment by RedFox0x20** [comment]
I'll start adding this. 😃

**Comment by audreyfeldroy** [comment]
Thanks again!
