### ISSUE TITLE
Add `backgroundImageAltText` property to Card

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#105]
In #104 @RedFox0x20 suggested exposing the alt text as a property of the Card component.

Perhaps something like `backgroundImageAltText` could be set for each card?

**Comment by pydanny** [comment]
Stackblitz has a free option for open source efforts: https://stackblitz.com/membership

I haven't tried running in this environment but it looks like Next support for it is in beta.

**Comment by marekrozmus** [comment]
@piyush26arora you can use [codesandbox](https://codesandbox.io/)

just press `create sandbox` - then `Import Project` and paste link to your repository branch
![codesandbox](https://user-images.githubusercontent.com/26272040/131210704-ee24e4fd-0f26-412c-8e2c-9844f37b9e19.jpg)

**Comment by piyush26arora** [comment]
@marekrozmus thanks, it turned out to be of great help.
This is the link of the code on codesandbox, same code is also available on my fork of this repo .
If it's fine, I will put PR for the same. 
https://codesandbox.io/s/prod-sea-5stbx

**Comment by audreyfeldroy** [comment]
Hi @piyush26arora! In this project there's no need to ask before submitting a PR. You can use PRs for anything: proposals for random ideas, sanity checks, unfinished PRs for questions like "Is this okay so far?", etc. 

I did check your code in codesandbox and it looks great. Kindly go ahead with the PR 😄
