### ISSUE TITLE
Add card for Health Education Workshop

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#11]
## Card title: 
Health Education Workshop

## Card text:
Produce 1 free health education workshop for an audience who urgently needs it, particularly for a community who faces major disparities in health conditions and care such as people of color, elders, young mothers including teen mothers, migrant workers, low-income families, foster families, unhoused families, and families of incarcerated parents. 

Your donation covers health-themed mini gift bags, raffle prizes to motivate people to attend a workshop, equipment to run the workshop such as trainer simulaids for edema and breast disease, costs to hire public health educators to prepare presentation and take-home materials, and any venue costs if not donated.

Card button: Produce 1 health workshop for $5000

Feel free to revise the text to fit better in a card, or generally to be more considerate/kind/appealing.

Button should go to a Stripe checkout page where the donor completes the $5000 payment. See the $5000 dropdown item for an example of how to implement it.

**Comment by Sukhamjot-Singh** [comment]
I would like to work on this issue.
Thank You.

**Comment by audreyfeldroy** [comment]
That would be a huge help, thank you @Sukhamjot-Singh. Try it out and let us know if you need help in any way.

**Comment by audreyfeldroy** [comment]
Merged, really appreciate your help!
