### ISSUE TITLE
Add frontend UI for Electronic Device Donation Form

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#115]
**What should we change and why?**

Create a form for people who want to donate electronic devices, with these fields:

* Name
* Email
* City
* State / Province / Region
* Country
* Tell us about each laptop, tablet, and/or smartphone you'd like to donate (textarea)

Link to this form from the Laptops for Families card, as a button replacing the shipping address.

This issue is just for the frontend UI, no backend.

**Please list any other [issues](https://github.com/margaritahumanitarian/helpafamily/issues) this may be related to**
- #34

**Comment by ozer619** [comment]
I would like to work on this issue.

**Comment by ozer619** [comment]
I would like to work on this issue.

**Comment by RedFox0x20** [comment]
Sure thing @ozer619 I will assign this to you. Many thanks!

**Comment by ozer619** [comment]
> Sure thing @ozer619 I will assign this to you. Many thanks!

i need guidance tho , after the person clicks the button what do i have to do?

**Comment by RedFox0x20** [comment]
@ozer619 the issue is currently only to implement the front end, no need to worry about the routing for now :)

**Comment by audreyfeldroy** [comment]
Yep, just the frontend. To start:
- Create a file called pages/give-devices.js. 
- Pattern it roughly after pages/thank-you.js
- Build the UI for the form on that page using DaisyUI.
- Don't set up form submission. The button will do nothing at this point. That's good!
- Send a PR with this code change.
