### ISSUE TITLE
Partner card: Shipping Address for Electronics Donations

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#118]
**What should we change and why?**

Implement a new card:

> Shipping Address for Electronics Donations
> 
> You can help us collect used laptops, tablets, and smartphones in your country by offering your organization's address as a mailing address for these devices. Volunteers will pick up the items periodically, fix them up, and provide them to families in need. You can optionally be involved with refurbishment and placement too if you'd like.
> 
> Email hi at mhfcares dot org to learn more.

This would go under a new navbar category called Partner With Us

**Please list any other [issues](https://github.com/margaritahumanitarian/helpafamily/issues) this may be related to**
- #117

**Comment by JasonZhu95** [comment]
Ok i understand viewing and forking from @Sukhamjot-Singh, but looking at the code added by #120 I don't see the shipping address for electronics donations card created.  It adds the ElectronicsDropOff card from issue #117 not the ShippingForElectronics Card.  So is this issue still open?  Am i missing something?  Sorry i'm not 100% sure still new to open source contributing.
