### ISSUE TITLE
Stretch background image to fit window

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#12]
Currently at some browser window widths, white bars are added to the left and right of the background image of the margarita daisy.

<img width="1409" alt=" 2021-08-11 at 08 21 43" src="https://user-images.githubusercontent.com/74739/129057016-0fa71779-e222-40c9-b07e-11b5b7f9346d.png">

I'm thinking the image should scale to 100% width with the bottom cropped off, though I'm flexible on that implementation. Generally making the background photo look better is the main objective here.

**Comment by GrungeKarma** [comment]
I submitted a pull request for this issue. Please let me know if you have any feedback.

**Comment by audreyfeldroy** [comment]
This is complete: thanks @GrungeKarma for the PR and @pydanny for the review and merge!
