### ISSUE TITLE
Refactor "Fund" cards to get data from a .json file

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#125]
The 5 cards that appear on https://helpafamily.margaritahumanitarian.org/fund are currently 5 different components. They're similar enough that they could be one component with different data.

- [ ] Create data/cards-fund.json containing the data for all the "Fund" cards
- [ ] Get the data for each Card component from data/cards-fund.json

**Comment by marekrozmus** [comment]
@audreyfeldroy Just wondering if we could use [contentful](https://www.contentful.com/) and make this site configurable :)

**Comment by audreyfeldroy** [comment]
I've never tried Contentful but it looks cool! Just signed up for an account and am looking into how to grant you admin rights on it.

**Comment by audreyfeldroy** [comment]
@marekrozmus What's your preferred email address for the Contentful invite? DM me via https://app.element.io/#/room/#mhf:matrix.org if you prefer

**Comment by marekrozmus** [comment]
@audreyfeldroy should we close this one - mine PR didn't do exactly what is written here but made this configurable.

**Comment by audreyfeldroy** [comment]
Yes, sorry forgot to close this! Thanks @marekrozmus 👍
