### ISSUE TITLE
Map of Electronics Gifting Cities

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#128]
Currently people are asking us where they can give or receive electronics. Create a simple map of the cities where people can give/receive electronics on a new page of the site:

- [ ] Create pages/electronics-gifting-cities.js
- [ ] Show all the locations on the map, using [this](https://cdn.contentful.com/spaces/knt9prkyuowf/environments/master/entries?access_token=9egwkeIujYc8xOfJcfv7QGdYD7fU_YnWa81NHXN7zgI) as the data source

FYI I also created [this json file](https://github.com/margaritahumanitarian/helpafamily/blob/main/data/laptop-cities.json) as a simplified version of the data, but it will probably go away soon.

**Comment by ozer619** [comment]
I would like to work on this issue.
