### ISSUE TITLE
Debate: Consider changing first_name/last_name fields to just "name"

### ISSUE THREAD

**Issue by pydanny** [margaritahumanitarian/helpafamily#134]
**What should we change and why?**

There are individuals with single names. There are also cultures with single names. Should we support them by having just a single name field? Let's discuss!

**Comment by RedFox0x20** [comment]
The standard for most sites is always separate First and Last names, however I do believe in many cases the last name field can be made optional. Simplifying it to a single, simple `Name` field makes sense in respect to this.

**Comment by audreyfeldroy** [comment]
Looking at the use cases:

* Sending laptop donors thank-you postcards, receipts, and letters via Lob API. Looks like they use a single "Name" field
* One-off mail via Pitney Bowes SendPro. Looks like Name is a single field too, nice:
<img width="481" alt=" 2021-08-29 at 08 28 52" src="https://user-images.githubusercontent.com/74739/131256025-ff7653b5-b688-42f8-9f0a-dfd2c6d99cc2.png">
* Interoperability with other in-kind donation and refurbishment APIs: unknown, still exploring what's out there.
