### ISSUE TITLE
Add GuideStar Seal of Transparency

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#150]
GuideStar gave us this widget to add to all our websites:

```
<a href="https://www.guidestar.org/profile/84-4323038" target="_blank"><img src="https://widgets.guidestar.org/gximage2?o=9874808&l=v4" /></a>
```

Add it to the footer however you think looks good, perhaps centered at the bottom. Consider using the Next.js [Image component](https://nextjs.org/docs/api-reference/next/image) and [Link component](https://nextjs.org/docs/api-reference/next/link).

**Comment by Akshansh99** [comment]
Hi @audreyfeldroy!
Can I work on this issue?

**Comment by audreyfeldroy** [comment]
Sure, go for it!

**Comment by audreyfeldroy** [comment]
Thanks again @Akshansh99!
