### ISSUE TITLE
Dockerize app

### ISSUE THREAD

**Issue by theflucs** [margaritahumanitarian/helpafamily#155]
Hi everyone,
I just forked the repo and looking forward to contribute.

The first thing I personally did was to add Dockerfile and docker-compose.yml to keep it in its own container and work safer.
Do you guys think it would be better to have it as a stander for the app?

If so I create a pull request.
Let me know,
Thanks and keep up the good work!
:smiley:

**Comment by RedFox0x20** [comment]
Hello @theflucs Please feel free to create the PR, this project houses a variety of skill levels and different knowledge about the technologies in use and available. It would be beneficial to have the PR there so we can read what the changes are and maybe contain some of the pros and cons of this sort of system. I.E. Does it work with existing infrastructure with ease etc.
