### ISSUE TITLE
Create a VolunteerCard component

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#172]
We're starting to run into use cases where different card types need different structure. As part of a larger refactor, we could use help with the first step of separating out VolunteerCard from Card:

- [ ] Break up `<Card>` into `<Card>` and `<VolunteerCard>`
- [ ] For `<VolunteerCard>` provide a `<PositionRequirements>` field that takes a bulleted list.
- [ ] Refactor `DoctorsAsVolunteers.js` to use the `<VolunteerCard>`

See #169 for an example, where I temporarily approved repurposing of `<CardAddress>` for volunteer position requirements as an interim solution for a style fix, even though it's not an address location.

Side note on use case: soon a VolunteerCard may also have other fields, such as whether that position is eligible for promotion into a student internship (see https://www.margaritahumanitarian.org/opportunities/internships)

**Comment by marekrozmus** [comment]
@audreyfeldroy Could we just add `<PositionRequirements>` component to `<Card>` component? There is no difference in usage of `<Card>` and `<VolunteerCard>` components so I think it will be mainly code duplication.
I mean if we'll have `<VolunteerCard>` that will be same as `<Card>` then what is the difference between:
```javascript
<Card>
  <PositionRequirements>sth here</PositionRequirements>
</Card>
```
and

```javascript
<VolunteerCard>
  <PositionRequirements>sth here</PositionRequirements>
</VolunteerCard>
```
? Or am I missing something 🙂

**Comment by RedFox0x20** [comment]
@marekrozmus I was also thinking that -- It does seem a bit unnecessary unless there were to be specific styling changes that needed to be made, however given the implementation in #174 I don't believe it would be necessary?

**Comment by marekrozmus** [comment]
@RedFox0x20 I would go only with following:
```
<Card>
  <PositionRequirements>sth here</PositionRequirements>
</Card>
```
as the `<VolunteerCard>` does not have anything additional.

**Comment by RedFox0x20** [comment]
> @RedFox0x20 I would go only with following:
> 
> ```
> <Card>
>   <PositionRequirements>sth here</PositionRequirements>
> </Card>
> ```
> 
> as the `<VolunteerCard>` does not have anything additional.

I agree with that, the extra element serves no purpose unless some styling differences were desired. I believe @theflucs has just followed what is highlighted in the issue here, however given the implementation is unnecessary. There is a time where this would be ideal (such as the requirements being passed as an array from where the elements are generated entirely from json) however the implementation does not suit it.
