### ISSUE TITLE
Card hover animation performance 

### ISSUE THREAD

**Issue by RedFox0x20** [margaritahumanitarian/helpafamily#176]
When hovering over the Cards on the main page while scrolling, sometimes some stutter occurs. We can see in the graph below that the CPU usage on `Render` Jumps up rapidly to 75-100% 
![image](https://user-images.githubusercontent.com/40431512/132556988-45257e6c-c2e9-47d7-81d2-b2adc91f98c0.png)

 Additionally this animation feels potentially optional, as it moves the text around,  I personally struggle with the text moving as it does as the animation takes a considerable amount of time to complete. Perhaps speeding the animation up would be a suitable solution so that the text remains static while also grabbing the users attention. That said the attention of the user is where they have placed there cursor and may have already started reading the text as the cursor enters the box which may again cause issues when trying to read the text.

**Comment by pydanny** [comment]
If anyone wants to submit a PR correcting the cards I'll review it ASAP. 

For what it's worth, I like the work done by @theflucs on the cards, but respect that other people may find it distracting or the text harder to read.

**Comment by theflucs** [comment]
Sorry to hear that, I didn't think about the performance as it is a very simple css transition offered by Tailwind and personally I find it quite smooth to use on my computer. But we can definitely look into it and, in the meanwhile,  just remove the Tailwind classes responsible for the effect. 
What do you think?
Sorry again

**Comment by pydanny** [comment]
@theflucs, No need to apologize! These kinds of issues happen all the time. In fact, it's on me as one of the maintainers of this repo for not using GitHub Actions to perform speed testing, or really any tests at all. So if anyone should be apologizing it is me: I'm sorry for not having the right infrastructure in place to support you. 🙏🏻 

Going forward we should add tests to look for this kind of thing, or at least open an issue.
