### ISSUE TITLE
High-conversion standard landing page?

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#187]
Reading https://unbounce.com/landing-page-examples/high-converting-landing-pages/ I think it would be nice to create a simple landing page.

The card pages would still be accessible from the nav, but the homepage would be simpler with the standard hero section.

I'm still trying to figure out what the best call-to-action in the hero section would be. Open to ideas about what would be most motivating to get site visitors to help families in need, one way or another. 

Currently we're rich in volunteers, poor in laptops & funding to help families, so perhaps something related to our biggest needs would be nice, but I'm open to whatever would make sense. Used laptop donations are probably the most urgent item, as we have space for a free community computer room, but our staff and all the families who come in for assistance are all taking turns sharing 2 laptops at the office 😅

**Comment by LowLifeArcade** [comment]
I can help this this!

**Comment by RedFox0x20** [comment]
@LowLifeArcade I have assigned this too you! Welcome to the project and thanks for the assistance!
