### ISSUE TITLE
Code cleanup: remove outer <div> elements?

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#19]
While reviewing #18 I realized that I had unintentionally started a pattern in `HygieneKitsCard.js` of wrapping cards in an empty outer `<div>`.

Is it best practice in React and/or Next.js to have a clean, class-free div wrapping everything? Or is it extraneous since the subsequent `<div className="card lg:card-side bordered">` already wraps everything?

For this issue:

- [ ] Comment with your thoughts about keeping vs. removing the outer `<div>`
- [ ] Submit one or more PRs removing them if appropriate

**Comment by Sukhamjot-Singh** [comment]
I believe there is no need for that extra <div> element. 
I can remove all the outer div elements and sumbit the PR.

**Comment by audreyfeldroy** [comment]
A PR for this would be very helpful, thank you @Sukhamjot-Singh!
