### ISSUE TITLE
Add all countries to laptop donation form

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#196]
https://www.countries-ofthe-world.com/all-countries.html has a list of all countries of the world.

Modify the laptop donation form dropdown to include all countries. This will save us time with manually adding countries as inquiries come in.

**Comment by Sahil-101** [comment]
I would like to work on this issue.

**Comment by ozer619** [comment]
Great @Sahil-101, let us know if you need any help .
