### ISSUE TITLE
Sort cards from smallest to largest donation cost

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#20]
To start, send a PR that moves the Hot Meal Day card above the Health Education Workshop card. 

After that, think about how we can implement automatic sorting of cards by price. There's zero obligation to work on this beyond that initial PR, but if you're interested, post ideas here. Or email me at audrey@mhfcares.org for an invite to our Slack text chat or Topia video chat.

**Comment by Sukhamjot-Singh** [comment]
PR #28 solves the primary task.
About the sorting, 
As we have hard coded the cards , the price that is inside the components cannot be retrieved to sort them.
I can work on any suggestions from you.

**Comment by audreyfeldroy** [comment]
Thank you for #28 @Sukhamjot-Singh!

About sorting, one possibility is to refactor strings from each card into something like a `data/cards.js`. 

https://www.pluralsight.com/guides/load-and-render-json-data-into-react-components has a good example of it. Search the article for "data.js". 

I'm flexible with other approaches, though.

**Comment by Sukhamjot-Singh** [comment]
> 
> 
> Thank you for #28 @Sukhamjot-Singh!
> 
> About sorting, one possibility is to refactor strings from each card into something like a `data/cards.js`.
> 
> https://www.pluralsight.com/guides/load-and-render-json-data-into-react-components has a good example of it. Search the article for "data.js".
> 
> I'm flexible with other approaches, though.

I will check this link out and try to work on the issue.

**Comment by Sukhamjot-Singh** [comment]
Well I have an easy solution for it.
I can create a list of cards and their amounts.
I will sort that list according to their respective amounts and render the components.

`const ListOfCards = [
  {
    card: <HealthWorkshopCard />,
    amount: 5000,
  },
  {
    card: <HygieneKitsCard />,
    amount: 153,
  },
  {
    card: <HotMealDayCard />,
    amount: 250,
  },
  
];`

**Comment by audreyfeldroy** [comment]
That sounds good @Sukhamjot-Singh. Try it and let me know how it goes. Happy to help if you get stuck on anything.

**Comment by audreyfeldroy** [comment]
This is done and merged, thanks to @Sukhamjot-Singh!
