### ISSUE TITLE
404 page needs to be responsive

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#203]
### Problem
The 404 page is not responsive creating issues on smaller devices.

### Solution
The design should be `display: block` or `flex-direction: column` on smaller resolutions.

### Proposed Solution
Since Tailwind is a mobile first framework, the flex container might be best used only after a certain size. Example: `md:flex`

This would be a great first issue for someone to get involved!

**Comment by vincentrohde** [comment]
@LowLifeArcade I would be happy to fix this 👍

**Comment by harishfalco** [comment]
Can I fix this @vincentrohde and send a PR to you?

**Comment by LowLifeArcade** [comment]
Hey guys, so I'm going to assign @vincentrohde to this as he did ask first. @harishfalco There are, however, many things to be done! Come over to our [Discord](https://discord.gg/E8z9yj36cv) and say hi and we can talk further. Both of you are welcome.
