### ISSUE TITLE
Our Discord Link is broken

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#205]
### Our README needs your help 🆘 

We have an expired invite link to our Discord and need to update it with this one https://discord.gg/E8z9yj36cv. It would be helpful also to check the other links as well.

**Comment by Jayita10** [comment]
Can I work on this issue?

**Comment by siddhantkhariwal** [comment]
Hey, can I fix this issue?

**Comment by LowLifeArcade** [comment]
Hey guys, I've assigned this to @siddhantkhariwal. @siddhantkhariwal we have many more issues coming that you can work on. Join our [Discord](https://discord.gg/Ss4xUSHGXU) and join our discussions!

**Comment by Jayita10** [comment]
Thank you @LowLifeArcade for assigning me. I have opened a PR. Please review 😃

**Comment by GeraAlcantara** [comment]
Please close the issue if is complete
