### ISSUE TITLE
Sitewide Height Layout Standard

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#208]
### Footer And Content Relationship

The site can use some work on the `PrimaryLayout` component to produce predictable behavior in the way content relates to the footer. Currently, on higher resolutions, the `Footer` floats below where the content stops. It should be done with `Tailwind` utility classes. This [question](https://stackoverflow.com/questions/47925751/how-to-fill-the-height-of-the-viewport-with-tailwind-css) might help guide you.

We're looking for each page to have:

- [ ] Footer sticky at the bottom at higher resolutions.
- [ ] Footer pushed out of view at lower resolutions when the content fills the screen (  css equivalent  -`overflow: scroll` ).

**Comment by Sahil-101** [comment]
I would like to work on this.

**Comment by LowLifeArcade** [comment]
This is some fun frontend stuff @Sahil-101 😆
