### ISSUE TITLE
Perform a dependency update

### ISSUE THREAD

**Issue by RedFox0x20** [margaritahumanitarian/helpafamily#212]
Could you please check the result of command:

`yarn why ansi-regex`

```
yarn why v1.22.10
[1/4] Why do we have the module "ansi-regex"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "ansi-regex@5.0.0"
info Reasons this module exists
   - "@testing-library#dom#pretty-format" depends on it
   - Hoisted from "@testing-library#dom#pretty-format#ansi-regex"
   - Hoisted from "wrap-ansi#strip-ansi#ansi-regex"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "20KB"
info Disk size with transitive dependencies: "20KB"
info Number of shared dependencies: 0
```

Maybe it would be better to update the dependency we are using  and not fixing the dependency of dependency ;)?

Please try update our dependencies and see if problem still exists :)

_Originally posted by @marekrozmus in https://github.com/margaritahumanitarian/helpafamily/pull/204#pullrequestreview-767130935_

**Comment by Aniket762** [comment]
Hey @RedFox0x20 I am interested can you please assign this to me?

**Comment by RedFox0x20** [comment]
Sure thing @Aniket762

**Comment by Aniket762** [comment]
Hey, @RedFox0x20 I am on it. Just wondering if I should add `dependabot.yml` for weekly or monthly module updates?

**Comment by RedFox0x20** [comment]
> Hey, @RedFox0x20 I am on it. Just wondering if I should add `dependabot.yml` in Github actions for weekly or monthly module updates? 

Currently an issue like this shows up on occasion, primarily if something new is added which isn't very often. Updates could also lead to issues if a module has updates that aren't backwards compatible.

As an alternative it would be nice to produce a set of instructions for updating modules and proper testing procedures.

**Comment by Aniket762** [comment]
Hey, @RedFox0x20 I have created pull request #220 please review it. I have updated `ansi-regex` and other testing packages and verified the code doesn't break and solves the issue. Let me know the changes will be more than happy to work on it.
