### ISSUE TITLE
Move cards from pages/ to components/

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#24]
Following the pattern that @Sukhamjot-Singh kindly set up of putting HygieneKitsCard.js in a `components/` folder:

- [x] Move HealthWorkshopCard.js and HotMealDayCard.js from `pages/` to `components/`
- [x] Update imports and check that the site still works

**Comment by Sukhamjot-Singh** [comment]
I also took the liberty to move MainDonationForm.js to components in PR #28.

**Comment by audreyfeldroy** [comment]
We really appreciate it, thank you @Sukhamjot-Singh!
