### ISSUE TITLE
Navbar responsiveness [BUG] 

### ISSUE THREAD

**Issue by Sahil-101** [margaritahumanitarian/helpafamily#240]
**What happened?**
Issue in responsiveness of Navbar in website.

**Steps to reproduce**
1. Open the website in google chrome or any other browser go into to Inspect section change the width size of the website to around 1300 pixels some text got overlapped, and if you decrease to 1000 pixels some gap is present at the right.
![image](https://user-images.githubusercontent.com/54836805/135878714-2833a049-0483-4e6a-877d-0fa356c1d07a.png)

**What did you expect to happen?**
Change into some hamburger menu perhaps.

**Comment by TueNguyen2911** [comment]
I'd like to work on this, please. Thank you!

**Comment by audreyfeldroy** [comment]
Hi, thanks for documenting and filing this @Sahil-101 @LowLifeArcade! 

@TueNguyen2911 heads up that @akshitarora921 is working on a related issue in #228...I recommend holding off until @akshitarora921 is done submitting that PR to avoid merge conflicts. In the meantime if you'd like, ask for guidance in https://discord.gg/HAeyn8Bf and we can point you at some newbie-friendly issues 🙂

**Comment by TueNguyen2911** [comment]
Thank you, I will wait for the PR
