### ISSUE TITLE
Create a Call To Action to apply to become a volunteer.

### ISSUE THREAD

**Issue by enoralecuyer** [margaritahumanitarian/helpafamily#249]
**What should we change and why?**
When people click on 'Give Your Time' and read the 'Doctors as Volunteers' card, they want to be able to contact the organization to offer their time. A Call to Action is missing to allow them to directly contact the organization from this page. For example, we could create a button that says "Apply Now" or "Contact Us".
![volunteer](https://user-images.githubusercontent.com/48727972/136086697-5e985dde-b26b-4b6d-b9b0-85efcd46ce89.png)

**Comment by LowLifeArcade** [comment]
@enoralecuyer Another great point! Anyone who wants to submit a PR with a solution is more than welcome!
