### ISSUE TITLE
500 server error on parter with us page

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#263]
**What happened?**
We get a 500 internal server error on Parter With Us page.

**Steps to reproduce**
Using the navbar navigate to `parter with us`.

**What did you expect to happen?**
Expect to see a web page but are presented with a 500 internal server error.

**Comment by Sahil-101** [comment]
I would look into this @LowLifeArcade.

**Comment by ozer619** [comment]
@LowLifeArcade I fixed this bug, seems like all the changes were in the dev branch(Contentful) and the production site fetches the data from the master branch I have reciprocated the required changes in the master branch of contentful and it seems to work now.
