### ISSUE TITLE
[BUG] Images stretching on Card component

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#265]
**What happened?**
Images on the card component are stretching.

<img width="786" alt="Screen Shot 2021-10-07 at 10 18 12 AM" src="https://user-images.githubusercontent.com/68655112/136433079-c1953a12-368d-4ee8-b115-83fee19c3d8c.png">

**What did you expect to happen?**
The image should:
- have the css equivalent `object-fit: cover`
- go to the edges of the card the way they currently do
- should not stretch

**Comment by ikurotime** [comment]
Hey! Can I work on this?
