### ISSUE TITLE
Pull request template not working[BUG] 

### ISSUE THREAD

**Issue by ozer619** [margaritahumanitarian/helpafamily#272]
**What happened?**
Pull request template not working.

**What did you expect to happen?**
While creating a Pull request the Pull request template should auto-fill the description.

**Comment by RedFox0x20** [comment]
Please see [this Pull Request](https://github.com/margaritahumanitarian/helpafamily/issues/194#issuecomment-922048113) in regards to how PR Templates work as they do not work the same as an Issue Template would.

#194
