### ISSUE TITLE
Mission Statement for /landing-page

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#279]
**What should we change and why?**
A mission statement section on the `landing-page` between the hero section and the testimonial section would be a nice addition to the site. 

If we look at [not for sale](https://www.notforsalecampaign.org/) the second section has a clear mission statement with a `learn more` button. The button can lead to the "what we do" section of the original page https://www.margaritahumanitarian.org/what-we-do

The Mission Statement section should have:

- [ ] A title with large font
- [ ] A descriptive section with placeholder copy
- [ ] A learn more button

**Comment by ehilst515** [comment]
Can I work on this? If so, is there an existing mission statement, or do I get to write one? 😄 Thanks!
