### ISSUE TITLE
Create a Laptops for Families program info page

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#282]
**What should we change and why?**
We should have an info page for our Laptops for Familes program. It should:

- [ ] be called `laptops-for-families.js` in `pages`
- [ ] have a navbar and footer as layout
- [ ] have a Hero section with image. Something like [this](https://www.notforsalecampaign.org/our-process/)
- [ ] have at least 3 description sections with lorem copy and graphics
- [ ] use color schemes similar to what is currently on the site (we're working on a style guide)

**Comment by siddhant-tripathy1** [comment]
can I work on it?

**Comment by shub78910** [comment]
Hey, @siddhant-tripathy1 I got stuck at another thing for now, if you like, you can pick this up. Would you?
