### ISSUE TITLE
[🐛 ]  Theme button conflicts with responsiveness on smaller screens

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#285]
**What happened?**
Our awesome new theme button needs some tweaking on smaller screens. 

<img width="326" alt="Screen Shot 2021-10-15 at 8 27 47 AM" src="https://user-images.githubusercontent.com/68655112/137514812-1dfe6949-3ac9-438d-994b-52f7db3e8f77.png">

<img width="334" alt="Screen Shot 2021-10-15 at 8 28 02 AM" src="https://user-images.githubusercontent.com/68655112/137514860-6788d83e-996a-4410-98aa-2e880e7589a2.png">

Possible solutions:
- Put `theme change` in the hamburger menu and omit the button on smaller screens
- Set the navbar title to a smaller font and center it between the hamburger and theme button
- Adjust padding on theme button or inspect what is going on with that portion of the navbar and adjust it accordingly

**Steps to reproduce**
1. Open website
2. Open dev tools
3. set responsiveness to lower resolution or select a smaller device

**What did you expect to happen?**
The menu, title and icon to live harmoniously.

**Comment by LowLifeArcade** [comment]
You got it @smily31. Thank you!

**Comment by smily31** [comment]
Okay
