### ISSUE TITLE
Add smaller donation levels to MainDonationForm.js

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#29]
Add a $5 and a $25 donation level as options in the main donation form.

**Comment by seth-reeise** [comment]
I submitted a pull request for this issue. This is my first pull request contributing to open source, any feedback is appreciated.

**Comment by pydanny** [comment]
We appreciate that this PR was small and focused on one ticket. The term for that is "atomic". 😄  ⚛️
