### ISSUE TITLE
✨ CSS help needed! An information section on home page for Hot Meal Day program

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#291]
## **A new section needed**
Our [Hot Meal Day](https://www.margaritahumanitarian.org/upcoming-events#h.3f0nxu3620tm) program is a recurring program in the foundation that should be highlighted on our main page.  For this we need a section below the hero section and above the program cards section. 

### Follow our [MHF CSS Guide](https://margaritahumanitarian.gitbook.io/help-a-family-manual/contributing-to-the-repository/mhf-css-guide)

Since we don't have a visual style guide yet, we might have to judge your work on the go. Experiment, but make sure it fits in to what we're doing. Use colors on the site or complementary colors if you're color savvy.  We do have our [MHF CSS Guide](https://margaritahumanitarian.gitbook.io/help-a-family-manual/contributing-to-the-repository/mhf-css-guide) to follow coding wise.  

The section should:
- [ ] be about ~~`80vh`~~ `60vh` in height
- [ ]  have appealing layout and design using:
    - [ ] large header text (think css `::after` with large quote block design)
    - [ ] 100 - 200 or so lines of lorem copy
    - [ ] possible stock photo used either as background or used in layout
- [ ] have a `read more` button

**Comment by panchoroo** [comment]
I'm interested in working on this issue
