### ISSUE TITLE
⚡️ 🏠 📄 ⚡️ Hot Meal Day Section

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#338]
**What should we change and why?**

We want to spruce it up. In the [Figma File](https://www.figma.com/file/nLwxUWpunk8SgvjVpyE2gd/MHF-Boards?node-id=0%3A1) we add a background which you will export as an svg to implement. Also, there are some detail changes with the buttons and a new font for the `quote`.

<img width="1440" alt="Screen Shot 2021-11-09 at 1 52 27 PM" src="https://user-images.githubusercontent.com/68655112/141017435-71049828-c23b-4dfa-81d5-07cf211c8722.png">

**Comment by akshitarora921** [comment]
@LowLifeArcadeCan I take this?

**Comment by LowLifeArcade** [comment]
We'll do one at a time @akshitarora921. Let's see who else can pick this one up.

**Comment by akshitarora921** [comment]
@LowLifeArcade Sure

**Comment by akshitarora921** [comment]
@LowLifeArcade 👀
