### ISSUE TITLE
⚡️ 🏠 📄 ⚡️ Large Info Section component with animation

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#339]
### Large Info Section

Using the [Figma Design File](https://www.figma.com/file/nLwxUWpunk8SgvjVpyE2gd/MHF-Boards?node-id=0%3A1) to put together a reusable component called `Large Info Section`. This component will have animation that brings the text into view when the component is scrolled into view using [intersection observer](https://medium.com/@cristinallamas/intersection-observer-vs-eventlistener-scroll-90aed9dc0e62).  Use [this video](https://www.youtube.com/watch?v=5DEq5cWNYt8&t=2049s) by Kevin Powell to guide you.

This info section should have:

- [ ] A boolean attribute that flips the layout to either left or right
- [ ] Animation that brings the content of the info box in from the right or left depending on the layout boolean
- [ ] A donate button that links the donate page
- [ ] A read more link that links to a program page (not yet implemented)

<img width="1440" alt="Screen Shot 2021-11-09 at 1 53 43 PM" src="https://user-images.githubusercontent.com/68655112/141020076-97e0dad2-16b0-40b3-8ded-982298936b94.png">

**Comment by Sahil-101** [comment]
Hey @LowLifeArcade could I work on this?

**Comment by LowLifeArcade** [comment]
Yeah @Sahil-101 definitely!

**Comment by LowLifeArcade** [comment]
Hey @Sahil-101. How's it going? Just checking in on you with this. :)

**Comment by akshitarora921** [comment]
@LowLifeArcade I can work on this, If @Sahil-101 says
