### ISSUE TITLE
Card for Laptops for Families

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#34]
Card title: Laptop for Families

Card description: Mail us a used or new laptop. We'll set up some donated laptops in our public computer room for families to use for free. Other donated laptops will go to families who don't have home computers, or who don't have enough computers for all their children to use.

(Feel free to revise the text to look better in a card, or to sound better.)

For this card, instead of a button it would show our office mailing address, which you can get from the Hygiene Kit card.

**Comment by briankarlsayen** [comment]
hi audreyfeldroy, I would like to work on this.

**Comment by audreyfeldroy** [comment]
Thank you @briankarlsayen, this issue is yours. If you get stuck, post here and we'll do our best to help.

**Comment by audreyfeldroy** [comment]
Oh, I just saw your PR, nice!

**Comment by audreyfeldroy** [comment]
I've reviewed your PR #48, nice work 🙂

**Comment by audreyfeldroy** [comment]
PR #48 is merged. Grateful for your work @briankarlsayen.
