### ISSUE TITLE
Extra horizontal space on our website

### ISSUE THREAD

**Issue by Sahil-101** [margaritahumanitarian/helpafamily#343]
**What happened?**
* Overflow of content horizontally and extra space present.
* Bug observed in browsers: Google Chrome, Firefox, Brave. Operating System Ubuntu 20.10.
 Screen Resolution > 2088*600
![Screenshot from 2021-11-16 00-22-59](https://user-images.githubusercontent.com/54836805/141838008-438e235f-bf58-42bf-97c1-cd9b9c916d17.png)

**Steps to reproduce**
1. Open [Help a family main website](https://helpafamily.margaritahumanitarian.org/).
2. Scroll horizontally and see the extra space.

**What did you expect to happen?**
* No horizontal scroll should be there.

**Comment by zac618** [comment]
I am 100% a newbie but would love to fix this one! 

Believe I know what needs adjusted if you want to assign this to me...if that's how this works?
