### ISSUE TITLE
Shorten text on Health Workshop card

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#35]
The text is a bit too long compared to the other cards and looks awkward. Cut out parts of it to tighten and strengthen the language so the card looks better.

**Comment by Harsh-Singh-Rajput** [comment]
hello audreyfeldroy in am working on your health workshop card but I didn't understand how to run, but I did change and shorten the health workshop card , will i commit the changes so that you can see that whether it solve your problem or not.

**Comment by audreyfeldroy** [comment]
Wonderful @Harsh-Singh-Rajput, thank you for working on this!

Let me help you get started.

Try this:
1. Download GitHub Desktop if you haven't yet.
2. Under Current Branch main, click the "New Branch" button.
3. Name the branch `shorten-health-workshop-card`
4. Click the "Create Branch" button.
5. Commit your changes to that branch.
6. Submit a pull request from that branch.

If you get stuck on any part of this, comment here and I can guide you further. I'm here for you.

**Comment by audreyfeldroy** [comment]
And yes, committing your changes and submitting a PR would be great. Then we can review it and give you feedback.

**Comment by Harsh-Singh-Rajput** [comment]
Ok Audrey I will commit changes tomorrow

> And yes, committing your changes and submitting a PR would be great. Then we can review it and give you feedback.

Ok then I will commit changes tomorrow and after that you can review and give feedback to me

**Comment by audreyfeldroy** [comment]
@Harsh-Singh-Rajput your PR is merged! Thanks so much.
