### ISSUE TITLE
Ability for radio buttons to revert

### ISSUE THREAD

**Issue by idiglove** [margaritahumanitarian/helpafamily#351]
**What should we change and why?**
In homepage, after clicking all the radio buttons there's no way for user to go back to previous state which is to choose certain categories only. Is this intended?

If you want the ability to revert, I can work on this

![image](https://user-images.githubusercontent.com/29911508/153198481-1d77bc0e-f76d-4275-bb29-44bd2afa71a2.png)

**Comment by ozer550** [comment]
Hi @idiglove, thanks!! for reaching out this looks like a good UI update idea to me, @LowLifeArcade what do you think about it?

**Comment by LowLifeArcade** [comment]
Hey @idiglove, yeah it's totally something you can work on! Thanks @ozer550 for addressing this 🏑
