### ISSUE TITLE
Set the font size of card's paragraph from 14px to standard size 16px.

### ISSUE THREAD

**Issue by NADS-PROGRAMMER** [margaritahumanitarian/helpafamily#358]
The reason for it is it is too small for small screen sizes and it has too much white space.
- #358

**Comment by prajapati55** [comment]
Hi NADS,
I would love to do work on this issue.

**Comment by NADS-PROGRAMMER** [comment]
Alright <3

**Comment by LowLifeArcade** [comment]
It's all yours @prajapati55 ✨
