### ISSUE TITLE
Change Health Workshop card to be per seat

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#36]
To improve the health workshop card, it would be nice to make the price per seat rather than per workshop.

**Comment by RedFox0x20** [comment]
What would the figures need to be changed for on this card?
It currently display `Create 1 workshop for $2000`, how many seats are there per workshop?

**Comment by audreyfeldroy** [comment]
Oh right, I just changed that price while I was attempting to shorten the button text. Looks like the button text is still too long and needs to be changed further anyway. Looking at it again, I think per seat may still be a better idea to make it more approachable.

For per-seat pricing, I think $100 per seat would be a good figure that donors could feel is fair and support.

(Technically it's costing MHF way more than that right now, but I see it eventually evening out.)

**Comment by audreyfeldroy** [comment]
Sorry, I reread this and realized I didn't answer your question properly @RedFox0x20. 

About seats per workshop, it's a bit complicated as our proposals vary a lot: a small workshop for a tiny multicultural church can be 20 seats, a large workshop for a public school may be 1000+ seats.

There's also the issue of health workshop length variation: some are series, some are one-time events.

Given the variability, upon reflection I think it's best to make separate cards for each type of workshop, as I did for the Fall Prevention class. I'll close this and modify the Health Workshop card to be specific to a particular proposal.

**Comment by RedFox0x20** [comment]
No need for apologies the intention of my question was to provide more information for anyone who wanted to take the task, sorry!

Multiple cards sounds like a better option. Additionally it may work out better for you to produce cards as and when the charity is available for certain sizes of events. There's a variety of factors determining the pricing required etc, which I'm sure you're far more aware of than I am haha.
