### ISSUE TITLE
Spacing out the side -bar navigation and introduce some transition

### ISSUE THREAD

**Issue by YTeyddie22** [margaritahumanitarian/helpafamily#360]
I think it would be a nice UX if a user clicks on the menu icon and the side-bar items transition in a well spaced out way. 

- #360

**Comment by mazkaaa** [comment]
Hi, I'd like to work on this idea. Can you provide the screenshot for this side-bar things and explain "well spaced out way" in details/references? thanks!

**Comment by YTeyddie22** [comment]
![Screenshot (258)](https://user-images.githubusercontent.com/69068114/157358134-266491e2-cc65-4f7c-88aa-263b2446b769.png)

**Comment by YTeyddie22** [comment]
that is the side-bar. am thinking if spacing it a little more and introducing a way of transitioning them so that they ease in and out  will make it a little bit nice

**Comment by YTeyddie22** [comment]
spacing out in a way they are not closely compacted as they are

**Comment by YTeyddie22** [comment]
Feel free to do it  :-)

**Comment by mazkaaa** [comment]
what....
