### ISSUE TITLE
Fall Prevention for Elders Card

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#37]
Following the pattern of the other cards, create a new card:

Fall Prevention for Elders

Provide one free, life-saving 6-week fall prevention class to an elderly person at high risk of falls.

Covers costs like insurance to meet city senior center requirements, and curriculum development and review.

1 class seat for $100

**Comment by RedFox0x20** [comment]
I'll put this together if work hasn't been started on it?

**Comment by audreyfeldroy** [comment]
#59 is merged, thanks @RedFox0x20!
