### ISSUE TITLE
Implement uniform card heights

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#38]
The problem has been described well by @GrungeKarma in #33:

> I am seeing an issue as this project moves forward. I am thinking we need to standardize the card size on a component level. As it sits, when I try to adjust the layout of the cards it looks bad because of the different card heights due to the different lengths of text in each card. It may be better to control the size of the cards directly so we can predict how they will act with flexbox. It would probably be easy to add a description length for each explanation and include a button for more information that brings up the expanded explanation as a popup or a separate page. Let me know if you have any ideas as well. Those are just the ideas going through my head.

Any solution that addresses this would be great, such as:

- Add a description length for each explanation and include a button for more information that brings up the expanded explanation as a popup or a separate page.
- Break up card description into short description and long description, where long description is shown only when you click "more" or similar
- Truncate text after a certain length with "..."
- Manually shorten the text of each card

Don't stress over getting this perfectly right: we can always iterate.

**Comment by audreyfeldroy** [comment]
We don't necessarily have to implement this. See #33 for more info about masonry as an alternative multi-column layout for varying card heights.

**Comment by GrungeKarma** [comment]
The cards are now housed in divs with predefined widths making them more standard. If we decided to go down the road of uniformity we will also have to implement a standard height and do some textual content editing.

**Comment by audreyfeldroy** [comment]
That PR was such a huge help @GrungeKarma. Agreed about your points about choosing a standard height and content editing.

I'd love to hear everyone's thoughts about uniform card heights vs. masonry vs. other approaches.

Also, I'm totally open to PRs with better writing or copy-editing as a means of partially or fully improving how the cards look.

**Comment by GrungeKarma** [comment]
I am going to take a look at this one as well.

**Comment by RedFox0x20** [comment]
I believe this is no-longer an issue due to #72

**Comment by audreyfeldroy** [comment]
Yep, thanks for posting that comment @RedFox0x20, helps me keep track. I know there's a way to auto-resolve issues from a PR merge. I suppose we should look into that at some point.

And thank you again @GrungeKarma for all your contributions. I know you're still new to much of this. I just wanted to say you're doing great. An open-source repo with this much activity is not easy to contribute to, especially while you're learning. Keep up the good work!

**Comment by GrungeKarma** [comment]
No problem, I am happy to help and this is a great learning experience.
