### ISSUE TITLE
Add MHF logo to main page

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#39]
The MHF logo is the globe with the heart, found at https://github.com/margaritahumanitarian

- [ ] Add this to the page somewhere. 
- [ ] Have it link to  https://www.margaritahumanitarian.org/

**Comment by riyaku11** [comment]
can i work on this issue?

**Comment by audreyfeldroy** [comment]
Yes, go for it @riyaku11 👍 

Let us know if you get stuck or need any help, we're here for you.

**Comment by audreyfeldroy** [comment]
I've put logo files in different sizes in https://github.com/margaritahumanitarian/media-kit/tree/main/logo-full-color

I can also resize those to any size you need.

How's it going @riyaku11? Post here or find me in [our chat room](https://app.element.io/#/room/#mhf:matrix.org) if you need any help, even with things like git.

**Comment by riyaku11** [comment]
I am not able to run the project locally, I am stuck at the yarn command .
this message is displayed : 'yarn' is not recognized as an internal or external command,
operable program or batch file.

**Comment by audreyfeldroy** [comment]
Hi @riyaku11! Try `npm install -g yarn` to install yarn. 

If that doesn't work, https://stackoverflow.com/questions/43313178/react-native-error-yarn-is-not-recognized-as-an-internal-or-external-command has some nice solutions.

**Comment by audreyfeldroy** [comment]
Hi @riyaku11! I unassigned this from you to take some pressure off your shoulders. Let's focus on getting your local setup working first. I can help you over chat or video if you'd like.

This issue is open to anyone interested in working on it 🙂

**Comment by audreyfeldroy** [comment]
Tips for anyone working on this issue:

* [Here](https://github.com/margaritahumanitarian/media-kit/blob/main/logo-full-color/MHF-Color-300x300.png) is a 300x300 version of the logo to copy into this repo
* If you'd like a smaller or larger dimension file, you can resize it or ask me for a particular size
* It's okay if it doesn't look perfect on the page. For example, I know the colors might not match. That's alright. There are other issues that will help with that, such as #83. And we can iterate on your work.

**Comment by audreyfeldroy** [comment]
Hey, so I decided to take this one due to the urgency and complexity of it. 

But all are welcome to iterate on what I did with improvement PRs. The logo I put in quickly is showing up blurry, and I didn't get a chance to fix it.
