### ISSUE TITLE
Add text about 501(c)(3) registration

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#40]
Add text somewhere on the page saying:

> Margarita Humanitarian Foundation is a 501(c)(3) nonprofit registered in the US.

It can be anywhere that you think looks good, such as:

- In a footer
- Below the page header somewhere

**Comment by Vaibhav9892** [comment]
I would really love to work on this issue.
Can I please work on it?

**Comment by audreyfeldroy** [comment]
Thank you @Vaibhav9892 for completing this in #42! Much appreciated.
