### ISSUE TITLE
Humanitarian Clinic card

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#49]
Create a new card on the page with this text:

Humanitarian Clinic

Provide a free, anonymous phone or video telehealth consultation for someone afraid to see a doctor, such as a migrant or refugee who lacks identification.

Help 1 Patient for $30

**Comment by JBCodeBook** [comment]
Hi Audrey, I'd like to help with this issue. Could I have a crack at it?

**Comment by JBCodeBook** [comment]
Hi again, I created a pull request just now. I'm happy to resolve any issues.

**Comment by audreyfeldroy** [comment]
I've merged #55. Thanks again @JBCodeBook!
