### ISSUE TITLE
Food Distribution Support card

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#51]
Create a card with the text:

Food Distribution Support

Help us cover our staffing costs for providing free food boxes for hungry families, such as paid time to manage volunteers for food distribution events or coordination with community groups.

Support Food Distribution for $150

**Comment by Vaibhav9892** [comment]
I would love to work on this issue. Can you assign it to me?

**Comment by audreyfeldroy** [comment]
Yep, it's all yours! Thanks for working on this @Vaibhav9892.

**Comment by audreyfeldroy** [comment]
This is complete in #53 thanks to @Vaibhav9892 and merged.
