### ISSUE TITLE
Enable DeepSource transformer for Prettier?

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#65]
From https://deepsource.io/gh/margaritahumanitarian/helpafamily/history/transforms :

> Enable transformers in `.deepsource.toml` to automatically transform all incoming code with auto code formatters.

This might be a good way to auto-run Prettier @marekrozmus? Unless you have another idea in mind?
See https://deepsource.io/docs/transformer/prettier

**Comment by marekrozmus** [comment]
I'll check it :) Please assign this issue to me as I cannot do that myself. Same with #27
