### ISSUE TITLE
Store radio button selection in Stripe

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#8]
Currently when people select a radio button like "Students in Need", the selection isn't saved in Stripe yet. 

This bug blocks us from promoting the site at all: we can't ask people to donate if we're not saving their donation selection.

Requirements:

- [ ] The selected radio button must be saved as some sort of metadata in Stripe. Possibly PaymentIntent object metadata? https://stripe.com/docs/api/payment_intents/object#payment_intent_object-metadata

This issue is sort of like a subset of #6.

**Comment by Quado1** [comment]
Hello, @audreyfeldroy. Did you fix it?

**Comment by audreyfeldroy** [comment]
Hi, yes this one is fixed, oops. Thanks for asking and helping me catch that.
